#!/usr/bin/env python

import sys
import socket

def filterline(line):
	left, right = line.split('{', 1)
	host, right = right.split('}', 1)
	addr = socket.gethostbyname(host)
	return left + addr + right

for line in sys.stdin:
	while '{' in line:
		line = filterline(line)
	sys.stdout.write(line)
